version: '3.8'

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./docgate:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docs:/app/docs
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
