"""empty message

Revision ID: 2791b3244d6e
Revises: f77693646591
Create Date: 2026-02-08 13:46:26.638554

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2791b3244d6e'
down_revision: str | Sequence[str] | None = 'f77693646591'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_dev', 'pay_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_dev', sa.Column('pay_method', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
