"""empty message

Revision ID: ddec103ed03f
Revises: 2791b3244d6e
Create Date: 2026-02-09 11:11:03.960880

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddec103ed03f"
down_revision: str | Sequence[str] | None = "2791b3244d6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_invite_codes_dev_bind_user_id"), table_name="invite_codes_dev")
  op.drop_index(op.f("ix_invite_codes_dev_code"), table_name="invite_codes_dev")
  op.drop_table("invite_codes_dev")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "invite_codes_dev",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("code", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column("lifetime", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column("has_used", sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column("bind_user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(
      ["bind_user_id"], ["users_dev.id"], name=op.f("invite_codes_dev_bind_user_id_fkey"), ondelete="SET NULL"
    ),
    sa.PrimaryKeyConstraint("id", name=op.f("invite_codes_dev_pkey")),
  )
  op.create_index(op.f("ix_invite_codes_dev_code"), "invite_codes_dev", ["code"], unique=False)
  op.create_index(op.f("ix_invite_codes_dev_bind_user_id"), "invite_codes_dev", ["bind_user_id"], unique=False)
  # ### end Alembic commands ###
