"""empty message

Revision ID: f77693646591
Revises:
Create Date: 2026-02-06 21:49:57.530203

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f77693646591"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_index(op.f("ix_invite_codes_dev_bind_user_id"), "invite_codes_dev", ["bind_user_id"], unique=False)
  op.drop_constraint(op.f("invite_codes_dev_bind_user_id_fkey"), "invite_codes_dev", type_="foreignkey")
  op.create_foreign_key(None, "invite_codes_dev", "users_dev", ["bind_user_id"], ["id"], ondelete="SET NULL")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, "invite_codes_dev", type_="foreignkey")
  op.create_foreign_key(
    op.f("invite_codes_dev_bind_user_id_fkey"), "invite_codes_dev", "users_dev", ["bind_user_id"], ["id"]
  )
  op.drop_index(op.f("ix_invite_codes_dev_bind_user_id"), table_name="invite_codes_dev")
  # ### end Alembic commands ###
